BEGIN {
    urlChars["20"] = " "
    urlChars["21"] = "!"
    urlChars["22"] = "\""
    urlChars["23"] = "#"
    urlChars["24"] = "$"
    urlChars["25"] = "%"
    urlChars["26"] = "&"
    urlChars["27"] = "'"
    urlChars["28"] = "("
    urlChars["29"] = ")"
    urlChars["2A"] = "*"
    urlChars["2B"] = "+"
    urlChars["2C"] = ","
    urlChars["2D"] = "-"
    urlChars["2E"] = "."
    urlChars["2F"] = "/"
    urlChars["30"] = "0"
    urlChars["31"] = "1"
    urlChars["32"] = "2"
    urlChars["33"] = "3"
    urlChars["34"] = "4"
    urlChars["35"] = "5"
    urlChars["36"] = "6"
    urlChars["37"] = "7"
    urlChars["38"] = "8"
    urlChars["39"] = "9"
    urlChars["3A"] = ":"
    urlChars["3B"] = ";"
    urlChars["3C"] = "<"
    urlChars["3D"] = "="
    urlChars["3E"] = ">"
    urlChars["3F"] = "?"
    urlChars["40"] = "@"
    urlChars["41"] = "A"
    urlChars["42"] = "B"
    urlChars["43"] = "C"
    urlChars["44"] = "D"
    urlChars["45"] = "E"
    urlChars["46"] = "F"
    urlChars["47"] = "G"
    urlChars["48"] = "H"
    urlChars["49"] = "I"
    urlChars["4A"] = "J"
    urlChars["4B"] = "K"
    urlChars["4C"] = "L"
    urlChars["4D"] = "M"
    urlChars["4E"] = "N"
    urlChars["4F"] = "O"
    urlChars["50"] = "P"
    urlChars["51"] = "Q"
    urlChars["52"] = "R"
    urlChars["53"] = "S"
    urlChars["54"] = "T"
    urlChars["55"] = "U"
    urlChars["56"] = "V"
    urlChars["57"] = "W"
    urlChars["58"] = "X"
    urlChars["59"] = "Y"
    urlChars["5A"] = "Z"
    urlChars["5B"] = "["
    urlChars["5C"] = "\\"
    urlChars["5D"] = "]"
    urlChars["5E"] = "^"
    urlChars["5F"] = "_"
    urlChars["60"] = "`"
    urlChars["61"] = "a"
    urlChars["62"] = "b"
    urlChars["63"] = "c"
    urlChars["64"] = "d"
    urlChars["65"] = "e"
    urlChars["66"] = "f"
    urlChars["67"] = "g"
    urlChars["68"] = "h"
    urlChars["69"] = "i"
    urlChars["6A"] = "j"
    urlChars["6B"] = "k"
    urlChars["6C"] = "l"
    urlChars["6D"] = "m"
    urlChars["6E"] = "n"
    urlChars["6F"] = "o"
    urlChars["70"] = "p"
    urlChars["71"] = "q"
    urlChars["72"] = "r"
    urlChars["73"] = "s"
    urlChars["74"] = "t"
    urlChars["75"] = "u"
    urlChars["76"] = "v"
    urlChars["77"] = "w"
    urlChars["78"] = "x"
    urlChars["79"] = "y"
    urlChars["7A"] = "z"
    urlChars["7B"] = "{"
    urlChars["7C"] = "|"
    urlChars["7D"] = "}"
    urlChars["7E"] = "~"
    urlChars["80"] = "`"
    urlChars["81"] = ""
    urlChars["82"] = "‚"
    urlChars["83"] = "ƒ"
    urlChars["84"] = "„"
    urlChars["85"] = "…"
    urlChars["86"] = "†"
    urlChars["87"] = "‡"
    urlChars["88"] = "ˆ"
    urlChars["89"] = "‰"
    urlChars["8A"] = "Š"
    urlChars["8B"] = "‹"
    urlChars["8C"] = "Œ"
    urlChars["8D"] = ""
    urlChars["8E"] = "Ž"
    urlChars["8F"] = ""
    urlChars["90"] = ""
    urlChars["91"] = "‘"
    urlChars["92"] = "’"
    urlChars["93"] = "“"
    urlChars["94"] = "”"
    urlChars["95"] = "•"
    urlChars["96"] = "–"
    urlChars["97"] = "—"
    urlChars["98"] = "˜"
    urlChars["99"] = "™"
    urlChars["9A"] = "š"
    urlChars["9B"] = "›"
    urlChars["9C"] = "œ"
    urlChars["9D"] = ""
    urlChars["9E"] = "ž"
    urlChars["9F"] = "Ÿ"
    urlChars["A1"] = "¡"
    urlChars["A2"] = "¢"
    urlChars["A3"] = "£"
    urlChars["A4"] = "¤"
    urlChars["A5"] = "¥"
    urlChars["A6"] = "¦"
    urlChars["A7"] = "§"
    urlChars["A8"] = "¨"
    urlChars["A9"] = "©"
    urlChars["AA"] = "ª"
    urlChars["AB"] = "«"
    urlChars["AC"] = "¬"
    urlChars["AD"] = "­"
    urlChars["AE"] = "®"
    urlChars["AF"] = "¯"
    urlChars["B0"] = "°"
    urlChars["B1"] = "±"
    urlChars["B2"] = "²"
    urlChars["B3"] = "³"
    urlChars["B4"] = "´"
    urlChars["B5"] = "µ"
    urlChars["B6"] = "¶"
    urlChars["B7"] = "·"
    urlChars["B8"] = "¸"
    urlChars["B9"] = "¹"
    urlChars["BA"] = "º"
    urlChars["BB"] = "»"
    urlChars["BC"] = "¼"
    urlChars["BD"] = "½"
    urlChars["BE"] = "¾"
    urlChars["BF"] = "¿"
    urlChars["C0"] = "À"
    urlChars["C1"] = "Á"
    urlChars["C2"] = "Â"
    urlChars["C3"] = "Ã"
    urlChars["C4"] = "Ä"
    urlChars["C5"] = "Å"
    urlChars["C6"] = "Æ"
    urlChars["C7"] = "Ç"
    urlChars["C8"] = "È"
    urlChars["C9"] = "É"
    urlChars["CA"] = "Ê"
    urlChars["CB"] = "Ë"
    urlChars["CC"] = "Ì"
    urlChars["CD"] = "Í"
    urlChars["CE"] = "Î"
    urlChars["CF"] = "Ï"
    urlChars["D0"] = "Ð"
    urlChars["D1"] = "Ñ"
    urlChars["D2"] = "Ò"
    urlChars["D3"] = "Ó"
    urlChars["D4"] = "Ô"
    urlChars["D5"] = "Õ"
    urlChars["D6"] = "Ö"
    urlChars["D7"] = "×"
    urlChars["D8"] = "Ø"
    urlChars["D9"] = "Ù"
    urlChars["DA"] = "Ú"
    urlChars["DB"] = "Û"
    urlChars["DC"] = "Ü"
    urlChars["DD"] = "Ý"
    urlChars["DE"] = "Þ"
    urlChars["DF"] = "ß"
    urlChars["E0"] = "à"
    urlChars["E1"] = "á"
    urlChars["E2"] = "â"
    urlChars["E3"] = "ã"
    urlChars["E4"] = "ä"
    urlChars["E5"] = "å"
    urlChars["E6"] = "æ"
    urlChars["E7"] = "ç"
    urlChars["E8"] = "è"
    urlChars["E9"] = "é"
    urlChars["EA"] = "ê"
    urlChars["EB"] = "ë"
    urlChars["EC"] = "ì"
    urlChars["ED"] = "í"
    urlChars["EE"] = "î"
    urlChars["EF"] = "ï"
    urlChars["F0"] = "ð"
    urlChars["F1"] = "ñ"
    urlChars["F2"] = "ò"
    urlChars["F3"] = "ó"
    urlChars["F4"] = "ô"
    urlChars["F5"] = "õ"
    urlChars["F6"] = "ö"
    urlChars["F7"] = "÷"
    urlChars["F8"] = "ø"
    urlChars["F9"] = "ù"
    urlChars["FA"] = "ú"
    urlChars["FB"] = "û"
    urlChars["FC"] = "ü"
    urlChars["FD"] = "ý"
    urlChars["FE"] = "þ"
    urlChars["FF"] = "ÿ"
}

function urlDecode(query)
{
    if (!query)
        return ""
    decoded = ""
    split(query, parts, "+")
    for (i in parts)
    {
        if (i > 1)
            decoded = decoded " "

        split(parts[i], subParts, "%")
        for (j in subParts)
        {
            if (j > 1)
            {
                code = substr(subParts[j], 0, 2)
                replacement = code in urlChars ? urlChars[code] : "?"
                sub("^" code, replacement, subParts[j])
            }
            decoded = decoded subParts[j]
        }

    }
    return decoded
}

